### ISSUE TITLE
Add character sheet integrations 

### ISSUE THREAD

**Issue by nkprasad12** [nkprasad12/dnd#37]
We can use the Google Sheets API to link tokens to characters and add features like run distance or dice checks

**Comment by Kaninapo** [comment]
Might be possible to circumvent this by using the Avrae bot:

is there any easy way to connect this to Discord? I could make a separate channel on TwoPlanksInn called "#gameboard" will all the same avrae functionality, then you could fetch that information to display. It be really cool if it works two ways, so that you could type on the gameboard, that gets sent to the discord, avrae does its thing, and you see it on the gameboard, effectively cutting out the need for discord beyond an avrae-host
